{% set name = "eido" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05823675f0df9ebfcdf1a9756025bdeb75a096482dfe9ce351b55474308a0ad7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eido = eido.__main__:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ubiquerg >=0.6.2
    - logmuse >=0.2.5
    - jsonschema >=3.0.1
    - peppy >=0.35.1

test:
  requires:
    - pip
  imports:
    - eido
  commands:
    - eido --help
    - pip check

about:
  home: https://github.com/pepkit/eido
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Validator for PEP objects

extra:
  recipe-maintainers:
    - stolarczyk
