{% set name = "eido" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5fbe83b3dd9b2e6f652615b57a672f4485cf664a8380ad2095146579e524880

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - eido = eido.__main__:main

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ubiquerg >=0.5.2
    - logmuse >=0.2.5
    - jsonschema >=3.0.1
    - peppy >=0.30.1
    - yacman >=0.6.7

test:
  requires:
    - pip
  imports:
    - eido
  commands:
    - eido --help
    - pip check

about:
  home: https://github.com/pepkit/eido
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Validator for PEP objects

extra:
  recipe-maintainers:
    - stolarczyk
